# Generated by Django 6.0 on 2025-12-11 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Optional ID from HRIS/Payroll/Source system used for mapping.', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On leave')], default='ACTIVE', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
                'unique_together': {('organisation', 'email')},
            },
        ),
    ]
